# Generated by Django 5.2.17 on 2026-08-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Full Stack Developer / Hacker', max_length=200)),
                ('sub_title', models.CharField(blank=True, help_text='e.g. Building scalable web apps', max_length=200)),
                ('about_text', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('resume_url', models.CharField(blank=True, help_text='URL or path to resume', max_length=255)),
                ('os_name', models.CharField(default='Ubuntu 22.04 LTS', max_length=100)),
                ('host', models.CharField(default='PortfolioVM x86_64', max_length=100)),
                ('kernel', models.CharField(default='Linux 5.15.0-generic', max_length=100)),
                ('shell', models.CharField(default='zsh 5.8.1', max_length=100)),
                ('de_wm', models.CharField(default='i3-gaps (X11)', max_length=100)),
                ('terminal', models.CharField(default='Alacritty', max_length=100)),
                ('cpu', models.CharField(default='Intel i7-12700H (20) @ 4.70GHz', max_length=100)),
                ('memory', models.CharField(default='16GB / 32GB (50%)', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Biography',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.CharField(help_text='e.g. Jan 2022', max_length=100)),
                ('end_date', models.CharField(default='Present', help_text='e.g. Dec 2023 or Present', max_length=100)),
                ('description', models.TextField(help_text='Description of achievements, use newline for list points')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, help_text='Static image URL/path or absolute web link', max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies used, e.g. Django, React, Postgres', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools/DevOps'), ('languages', 'Core Languages')], max_length=20)),
                ('proficiency', models.IntegerField(help_text='Percentage from 0 to 100')),
                ('icon_class', models.CharField(help_text="FontAwesome class e.g., 'fab fa-python'", max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
